//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Dark1Git
{
	public class Branch
	{
		public string Name;
		public string CommitHash;
		public string CommitMessage;
		public bool IsActiveBranch;
		public Branch (string name, string hash, string commitMessage, bool IsActiveBranch = false)
		{
			this.Name = name;
			this.CommitHash = hash;
			this.CommitMessage = commitMessage;
		}

		public override string ToString ()
		{
			return string.Format ("[Branch]: "+Name);
		}
	}
}

