//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Dark1Git
{
	public class File
	{
		public string Path;
		public string Status;

		public File (string path, string status)
		{
			Path = path;
			Status = status;
		}
		public override string ToString ()
		{
			return string.Format ("[File]["+Status+"]: "+Path);
		}
	}
}

